import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { belleza } from "./ui/fonts";
import MainNav from "./ui/components/main-nav";
import Footer from "./ui/components/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${belleza.className} antialiased`}
      >
      <MainNav />
        {children}
      <Footer />
      </body>
    </html>
  );
}
